require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DishImagesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # DishImage. As you add validations to DishImage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DishImagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all dish_images as @dish_images" do
      dish_image = DishImage.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:dish_images)).to eq([dish_image])
    end
  end

  describe "GET #show" do
    it "assigns the requested dish_image as @dish_image" do
      dish_image = DishImage.create! valid_attributes
      get :show, {:id => dish_image.to_param}, valid_session
      expect(assigns(:dish_image)).to eq(dish_image)
    end
  end

  describe "GET #new" do
    it "assigns a new dish_image as @dish_image" do
      get :new, {}, valid_session
      expect(assigns(:dish_image)).to be_a_new(DishImage)
    end
  end

  describe "GET #edit" do
    it "assigns the requested dish_image as @dish_image" do
      dish_image = DishImage.create! valid_attributes
      get :edit, {:id => dish_image.to_param}, valid_session
      expect(assigns(:dish_image)).to eq(dish_image)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new DishImage" do
        expect {
          post :create, {:dish_image => valid_attributes}, valid_session
        }.to change(DishImage, :count).by(1)
      end

      it "assigns a newly created dish_image as @dish_image" do
        post :create, {:dish_image => valid_attributes}, valid_session
        expect(assigns(:dish_image)).to be_a(DishImage)
        expect(assigns(:dish_image)).to be_persisted
      end

      it "redirects to the created dish_image" do
        post :create, {:dish_image => valid_attributes}, valid_session
        expect(response).to redirect_to(DishImage.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved dish_image as @dish_image" do
        post :create, {:dish_image => invalid_attributes}, valid_session
        expect(assigns(:dish_image)).to be_a_new(DishImage)
      end

      it "re-renders the 'new' template" do
        post :create, {:dish_image => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dish_image" do
        dish_image = DishImage.create! valid_attributes
        put :update, {:id => dish_image.to_param, :dish_image => new_attributes}, valid_session
        dish_image.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested dish_image as @dish_image" do
        dish_image = DishImage.create! valid_attributes
        put :update, {:id => dish_image.to_param, :dish_image => valid_attributes}, valid_session
        expect(assigns(:dish_image)).to eq(dish_image)
      end

      it "redirects to the dish_image" do
        dish_image = DishImage.create! valid_attributes
        put :update, {:id => dish_image.to_param, :dish_image => valid_attributes}, valid_session
        expect(response).to redirect_to(dish_image)
      end
    end

    context "with invalid params" do
      it "assigns the dish_image as @dish_image" do
        dish_image = DishImage.create! valid_attributes
        put :update, {:id => dish_image.to_param, :dish_image => invalid_attributes}, valid_session
        expect(assigns(:dish_image)).to eq(dish_image)
      end

      it "re-renders the 'edit' template" do
        dish_image = DishImage.create! valid_attributes
        put :update, {:id => dish_image.to_param, :dish_image => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested dish_image" do
      dish_image = DishImage.create! valid_attributes
      expect {
        delete :destroy, {:id => dish_image.to_param}, valid_session
      }.to change(DishImage, :count).by(-1)
    end

    it "redirects to the dish_images list" do
      dish_image = DishImage.create! valid_attributes
      delete :destroy, {:id => dish_image.to_param}, valid_session
      expect(response).to redirect_to(dish_images_url)
    end
  end

end
